module: MaterialMotion<%= componentName %>
module_version: <%= version %>
umbrella_header: src/MaterialMotion<%= componentName %>.h
objc: true
sdk: iphonesimulator
github_url: https://github.com/<%= repoOwner %>/<%= repoName %>
github_file_prefix: https://github.com/<%= repoOwner %>/<%= repoName %>/tree/v<%= version %>
